source "https://rubygems.org"

gem "fluentd", "1.9.3"
gem "oj", "3.8.1"
gem "ffi"

# plugins
gem "fluent-plugin-concat", "~> 2.4.0"
gem "fluent-plugin-detect-exceptions", "~> 0.0.12"
gem "fluent-plugin-grok-parser", "~> 2.6.0"
gem 'fluent-plugin-json-in-json-2', ">= 1.0.2"
gem "fluent-plugin-kubernetes_metadata_filter", "~> 2.3.0"
gem "fluent-plugin-multi-format-parser", "~> 1.0.0"
gem "fluent-plugin-prometheus", "~> 1.6.1"
gem "fluent-plugin-record-modifier", "~> 2.0.0"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.2.0"
gem "fluent-plugin-systemd", "~> 1.0.1"

# cloudwatch
gem "aws-sdk-cloudwatchlogs", "~> 1.0"
gem "fluent-plugin-cloudwatch-logs", "~> 0.8.0"

# elasticsearch
gem "elasticsearch", "~> 6.0"
gem "fluent-plugin-elasticsearch", "~> 4.0.3"

# remote_syslog
gem "fluent-plugin-remote_syslog", "~> 1.0.0"
