source "https://rubygems.org"

# Same pins as fluent/fluentd-kubernetes-daemonset v1.19.3-debian-cloudwatch-1.1
# (docker-image/v1.19/debian-cloudwatch/Gemfile), plus syslog_protocol for
# plugins/out_syslog.rb.
gem "fluentd", "1.19.3"

gem "ffi"
gem "oj", "~> 3.17.3"
gem "rexml", "~> 3.4.1"

gem "fluent-plugin-multi-format-parser", "~> 1.0.0"
gem "fluent-plugin-concat", "~> 2.6.0"
gem "fluent-plugin-grok-parser", "~> 2.6.2"
gem "fluent-plugin-prometheus", "~> 2.2.1"
gem "fluent-plugin-json-in-json-2", ">= 1.0.2"
gem "fluent-plugin-record-modifier", "~> 2.2.0"
gem "fluent-plugin-detect-exceptions", "~> 0.0.16"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.4.0"
gem "fluent-plugin-kubernetes_metadata_filter", "~> 3.8.0"
gem "fluent-plugin-parser-cri", "~> 0.1.1"
gem "fluent-plugin-systemd", "~> 1.1.1"

# cloudwatch
gem "aws-sdk-cloudwatchlogs", "~> 1.124.0"
gem "fluent-plugin-cloudwatch-logs", "~> 0.15.0"

# syslog (plugins/out_syslog.rb)
gem "syslog_protocol", "~> 0.9.2"
